### PR TITLE
Fix kwargs usage for Ruby 2.7

### PR DESCRIPTION
**Pull request by mkanakana**
Fix deprecation warnings.

### CODE REVIEW

**Comment by apotonick** [comment]
Oh cool, so Ruby 2.7 requires you to explicitly define those args as kw args if you don't pass a hash, syntactically (as in `bla(a: ..., b: ..)`?

**Comment by seuros** [comment]
yes. Else it will throw a small warning.

**Comment by apotonick** [comment]
Only a small one? :laughing:

**Comment by seuros** [comment]
Well it depend on your font size and screen resolution.

**Comment by yogeshjain999** [comment]
Hmm, but in case any hash contains a key other than of type `symbol`, it'll break, right ?

**Comment by yogeshjain999** [comment]
I was having a memory of they reverting this change, I found that thread,
https://discuss.rubyonrails.org/t/new-2-7-3-0-keyword-argument-pain-point/74980

**Comment by mkanakana** [comment]
> Hmm, but in case any hash contains a key other than of type `symbol`, it'll break, right ?

Yes, but a hash with non-symbol keys seems already unacceptable.

```ruby
activity = Class.new(Trailblazer::Activity::Path) do
  step task: :a
  def a(*); true; end
end

activity.([{ 'key' => 1 }, {}]) # TypeError: hash key "key" is not a Symbol
```

**Comment by yogeshjain999** [comment]
Yes, good point. We need to fix that with trb-context.

Overall, I'm not sure if splatting all the hashes would cause any issues in Rubies <= 2.6. What do you think @apotonick @seuros ? Maybe we need run tests for dependencies of `dsl-linear` too.

**Pull request merged**
