### PR TITLE
Problem when patching a nested subprocess

### PR DESCRIPTION
**Pull request by jkraemer**
This PR has a failing test case I created to illustrate my problem.

I have an Operation that calls another one via `Subprocess`, which in turn uses `Subprocess` to call a third op. That third op maps `Output(:failure)` to `End(:not_found)`. 

This all works fine until I try to patch the innermost operation when calling it from the outermost. Even an empty patch will result in an IllegalSignalError:

~~~
Unrecognized Signal `#<Trailblazer::Activity::End semantic=:not_found>` returned
Registered signals are,
- #<Trailblazer::Activity::End semantic=:failure>
- #<Trailblazer::Activity::End semantic=:success>
~~~

Am I just holding it wrong or is it indeed a bug?

### CODE REVIEW

**Comment by apotonick** [comment]
Oh, great spotting, and perfect PR! :heart: I have a suspicion that we're overriding custom wiring when patching! :sweat_smile: 

Somehow OT, but may I ask how you use patching in your project? Out of curiosity and to understand how we can improve TRB. :beers:

**Comment by jkraemer** [comment]
Sure :) I have an operation which looks up some records and also does a policy check. I'm patching that to account for changing the level of access, e.g. *may read* vs *may write*.

**Comment by apotonick** [comment]
@jkraemer Can you elaborate and ausführen that a bit more and show me the op class skeletons and where/how you implement the policies?

**Comment by yogeshjain999** [comment]
Thanks for reporting this bug @jkraemer . Created the PR #44 to fix it. 🍻

**Comment by jkraemer** [comment]
> @jkraemer Can you elaborate and ausführen that a bit more and show me the op class skeletons and where/how you implement the policies?

OK, here we go. Let me know if there's a better way to achieve what I'm doing - it's my first trailblazer project :)

I put my policies in their ActiveRecord classes since they are pretty simple for now.

~~~ruby
class Application < ApplicationRecord
  class Policy
    def initialize(user, model)
      @application = model
      @user = user
    end
    def show?
      @user.in_organization?(@application.organization)
    end
    def update?
      show? and not @application.submitted?
    end
    alias submit? update?
  end
end
~~~

My finder operation that I want to patch. The `RequireLogin()` macro comes from the `ApplicationOperation` base class and just checks for presence of the current user in the context.

~~~ruby
module Application::Operation
  class Find < ApplicationOperation
    step RequireLogin()
    step :find_application, id: :find_application
    step Policy::Pundit(Application::Policy, :show?), id: :policy_check
    def find_application(ctx, params:, **)
      id = params[:application_id].presence || params[:id]
      ctx[:model] = Application.find_by_id id
    end
  end
end
~~~

The patching operation is `Submit`, which has a nested `Present` op that is also used stand-alone for the pre-submit screen.

~~~ruby
module Application::Operation
  class Submit < ApplicationOperation

    class Present < ApplicationOperation
      step Subprocess(Application::Operation::Find),
        id: :find_application,
        input: %i[ params current_user ],
        output: %i[ model ],
        Output(:unauthenticated) => End(:unauthenticated),
        Output(:failure)         => End(:not_found)
      # some more steps...
    end

    # call Present, but replace the policy check with one for :submit permission
    step Subprocess(
      Present, patch: {
        %i[find_application] => ->{
          step Policy::Pundit(Application::Policy, :submit?), replace: :policy_check
        }
      }
    ), Output(:unauthenticated) => End(:unauthenticated),
       Output(:not_found) => End(:not_found),
       Output(:invalid_data) => End(:invalid_data),
       Output(:failure) => End(:not_found)
    # more steps...
  end
end
~~~

The `Output(:failure) => End(:not_found)` mappings I added to work around the lost mapping after patching the operation.

**Comment by jkraemer** [comment]
Oh and btw @apotonick - is there any way to shorten the various `Output(:foo) => End(:foo)` mappings of each possible signal a Subprocess might return? As it is now I feel the need for a way to wire all, or a given list of outputs to their corresponding ends with a little less boilerplate, maybe like this:

~~~ruby
Subprocess(Present), Ends(:not_found, :unauthenticated)
~~~
would be equivalent to
~~~ruby
Subprocess(Present), Output(:not_found) => End(:not_found), Output(:unauthenticated) => End(:unauthenticated)
~~~

That might feel similar to the way input / output arguments to the Subprocess can be given as either a list and / or a hash for renaming them.

 Or is there a better way to get around this?

**Comment by yogeshjain999** [comment]
Released [v0.3.5](https://github.com/trailblazer/trailblazer-activity-dsl-linear/releases/tag/v0.3.5) with the fix

**Comment by apotonick** [comment]
@jkraemer Oh, so that's interesting. We do have a new component now, `endpoint` that basically does what you're building yourself. https://trailblazer.to/2.1/docs/endpoint.html I am currently writing a tutorial for how to use it, but the docs online are actually enough to get it working. Other than that, your code looks pretty good!

**Comment by jkraemer** [comment]
@apotonick thanks! I had a look at endpoint before but back then the docs were still under construction I believe. And/or it was just information overload at the time. Now after having worked with trb for a while it starts to make sense :)

**Comment by apotonick** [comment]
> Oh and btw @apotonick - is there any way to shorten the various `Output(:foo) => End(:foo)` mappings of each possible signal a Subprocess might return? As it is now I feel the need for a way to wire all, or a given list of outputs to their corresponding ends with a little less boilerplate, maybe like this:
> 
> ```ruby
> Subprocess(Present), Ends(:not_found, :unauthenticated)
> ```
> 
> would be equivalent to
> 
> ```ruby
> Subprocess(Present), Output(:not_found) => End(:not_found), Output(:unauthenticated) => End(:unauthenticated)
> ```
> 
Cool, I like this shortcut. Can you open a PR in this gem where we can discuss? I can also point you to the right spot in the code in case you want to plan. :heart:

**Pull request closed without merging**
